### ISSUE TITLE
feat: add links to website and GitHub

### ISSUE THREAD

**Issue by schalkneethling** [schalkneethling/developer-toolchest#213]
Currently, we generally link to a service's website. This is great, but it would be great to also link to their GitHub, Gitlab, etc. repositories if they exist.

**Comment by cptleo92** [comment]
@schalkneethling, I can tackle this.

I'm thinking of adding this to the card:
![image](https://user-images.githubusercontent.com/96504457/217940001-1465c109-a64e-41e2-81eb-34d146acc9ee.png)

It doesn't look too great if the title is long, but otherwise I think it does the job.

As for `tools.json`, it's just a matter of adding a `repo` property to each tool. A bit tedious but fairly simple otherwise. 

Let me know your thoughts and I'll get started!
